name: hoonapp010704
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.13
  provider: ^6.1.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  flutter_barcode_scanner: ^2.0.0
  http: ^1.1.0
  # Firebase
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/
